name: CI Test (no release)

on:
  push:
    branches:
      - ci_test
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  build-win-amd64:
    uses: ./.github/workflows/_build-platform.yaml
    with:
      platform: win-amd64
      ref: ${{ github.sha }}
      publish_mode: artifact
      artifact_name: ci-test-win-amd64

  build-linux-amd64:
    uses: ./.github/workflows/_build-platform.yaml
    with:
      platform: linux-amd64
      ref: ${{ github.sha }}
      publish_mode: artifact
      artifact_name: ci-test-linux-amd64

  build-linux-arm64:
    uses: ./.github/workflows/_build-platform.yaml
    with:
      platform: linux-arm64
      ref: ${{ github.sha }}
      publish_mode: artifact
      artifact_name: ci-test-linux-arm64

  build-mac-amd64:
    uses: ./.github/workflows/_build-platform.yaml
    with:
      platform: mac-amd64
      ref: ${{ github.sha }}
      publish_mode: artifact
      artifact_name: ci-test-mac-amd64

  build-mac-arm64:
    uses: ./.github/workflows/_build-platform.yaml
    with:
      platform: mac-arm64
      ref: ${{ github.sha }}
      publish_mode: artifact
      artifact_name: ci-test-mac-arm64
